#include QMK_KEYBOARD_H

#include "g/keymap_combo.h"
#include "keymap_steno.h"
#include "merlinvn.h"

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

/* ,-----------------------------------------.  ,-----------------------------------------.
 * |  Q   |  W   |  F   |  P   |  B   | LGUI |  | APP  |  J   |  L   |  U   |  Y   | QUOT |
 * |------+------+------+------+------+------|  |------+------+------+------+------+------|
 * |------+------+------+------+------+------|  |------+------+------+------+------+------|
 * |  A   |  R   |  S   |  T   |  G   | CAPS |  | SCLN |  M   |  N   |  E   |  I   |  O   |
 * |LGUI_T|LALT_T|LCTL_T|LSFT_T|  V   |HYPR(K|  |MEH(KC|  K   |RSFT_T|RCTL_T|LALT_T|RGUI_T|
 * |------+------+------+------+------+------|  |------+------+------+------+------+------|
 * | LEFT | RGHT | HOME |MED_ES|NAV_SP|SFT_TA|  | DEL  |SYM_BS|FN_ENT| END  | DOWN |  UP  |
 * `-----------------------------------------'  `-----------------------------------------'
 *                                                                 generated by [keymapviz] */

  [_BASE0] = LAYOUT_ortho_4x12(\
      KC_Q, KC_W, KC_F, KC_P, KC_B,              TO(_BASE2), KC_NO,      KC_Z, KC_L, KC_U, KC_Y, KC_ENT,
      KC_A, KC_R, KC_S, NUM_T, KC_G,              KC_NO, KC_NO,          KC_M, KC_N, KC_H, KC_I, KC_O,
      KC_QUOT,KC_X,KC_C, KC_D,KC_V,               KC_NO, KC_NO,          KC_SLSH, KC_J, KC_K, KC_COMM, KC_DOT,
      KC_LEFT, KC_RGHT, KC_MEH , OSL(_FN), NAV_SPC, KC_NO, KC_NO,      KC_E, OSL(_SYMBOLS), KC_HYPR, KC_DOWN, KC_UP
      ),


/* ,-----------------------------------------.  ,-----------------------------------------.
 * |  Q   |  W   |  E   |  R   |  T   |      |  |      |  Y   |  U   |  I   |  O   |  P   |
 * |------+------+------+------+------+------|  |------+------+------+------+------+------|
 * |  A   |  S   |  D   |  F   |  G   |      |  |      |  H   |  J   |  K   |  L   | QUOT |
 * |------+------+------+------+------+------|  |------+------+------+------+------+------|
 * |      |      |      |LSFT_T|  B   |      |  |      |  N   |RSFT_T|      |      |      |
 * |------+------+------+------+------+------|  |------+------+------+------+------+------|
 * |      |      |      |      |      |      |  |      |      |      |      |      |      |
 * `-----------------------------------------'  `-----------------------------------------'
 *                                                                 generated by [keymapviz] */

	[_BASE1] = LAYOUT_ortho_4x12(\
      KC_Q, KC_W, KC_E, KC_R, KC_T,                  KC_NO, KC_NO,          KC_Y, KC_U, KC_I, KC_O, KC_P,
      KC_A, KC_S, KC_D, KC_F, KC_G,                  KC_NO, KC_NO,          KC_H, KC_J, KC_K, KC_L, KC_QUOT,
      KC_Z, KC_X, KC_C, KC_V, KC_B,                  KC_NO, KC_NO,          KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
      TO(_BASE2), KC_LEFT, KC_RGHT, NAV_ESC, KC_SPC, KC_NO, KC_NO,        OSL(_SYMBOLS), FN_ENT, KC_END, KC_DOWN, KC_UP
      ),


/* Plover layer (http://opensteno.org)
 * ,-----------------------------------------------------------------------------------.
 * |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |   #  |
 * |------+------+------+------+------+-------------+------+------+------+------+------|
 * |  FN  |   S  |   T  |   P  |   H  |   *  |   *  |   F  |   P  |   L  |   T  |   D  |
 * |------+------+------+------+------+------|------+------+------+------+------+------|
 * |      |   S  |   K  |   W  |   R  |   *  |   *  |   R  |   B  |   G  |   S  |   Z  |
 * |------+------+------+------+------+------+------+------+------+------+------+------|
 * | Exit |      |      |   A  |   O  |             |   E  |   U  |  PWR | RES1 | RES2 |
 * `-----------------------------------------------------------------------------------'
 */

[_BASE2] = LAYOUT_ortho_4x12(\
  STN_N1,  STN_N2,  STN_N3,  STN_N4,  STN_N5,  STN_N6,  STN_N7,  STN_ST3,  STN_ST4,  STN_NA,  STN_NB,  STN_NC ,
  MO(_STE_NAV),  STN_S1,  STN_TL,  STN_PL,  STN_HL,  STN_ST1, STN_ST3, STN_FR,  STN_PR,  STN_LR,  STN_TR,  STN_DR ,
  MO(_STE_SYM), STN_S2,  STN_KL,  STN_WL,  STN_RL,  STN_ST2, STN_ST4, STN_RR,  STN_BR,  STN_GR,  STN_SR,  STN_ZR ,
  TO(_BASE0), XXXXXXX, XXXXXXX, STN_AO,STN_A,  STN_O,   STN_E,   STN_U,   STN_EU,XXXXXXX, STN_RE1, STN_RE2
),

  [_NAVIGATION] = LAYOUT_ortho_4x12(\
      SW_WIN, SW_TAB, KC_DEL, KC_TAB, KC_CAPS,         KC_NO, KC_NO,      KC_PGUP, KC_HOME, KC_UP, KC_END, KC_BSPC,
      LGUI(KC_1), LGUI(KC_2), LGUI(KC_3), LGUI(KC_4), LGUI(KC_5),   KC_NO, KC_NO,      KC_PGDN, KC_LEFT, KC_DOWN,  KC_RGHT, KC_INS,
      LGUI_9, LALT_8, LCTL_7, LSFT_6, KC_0,            KC_NO, KC_NO,    KC_5, RSFT_1, RCTL_2, LALT_3, RGUI_4,
      KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS,           KC_NO, KC_NO,      KC_TRNS, KC_ENT, KC_NO, KC_NO, KC_NO),

  [_FN] = LAYOUT_ortho_4x12(\
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,          KC_NO, KC_NO, KC_PSCR, KC_F9, KC_F10, KC_F11, KC_F12,
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,          KC_NO, KC_NO, KC_SLCK, KC_F5, KC_F6, KC_F7, KC_F8,
      OS_LGUI, OS_LALT, OS_LCTL, OS_LSFT,  KC_NO, KC_NO, KC_NO, KC_PAUS, KC_F1, KC_F2, KC_F3, KC_F4,
      KC_NO, KC_NO, KC_NO, KC_TRNS, KC_NO,        KC_NO, KC_NO, KC_APP, MO(_MEDIA), KC_NO, KC_NO, KC_NO),

  [_MEDIA] = LAYOUT_ortho_4x12(\
      DF(0), DF(1), DF(2), KC_NO, KC_NO, KC_NO, KC_NO, RGB_TOG, KC_NO, RGB_SAI, RGB_HUI, RGB_VAI,
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, RGB_SAD, RGB_HUD, RGB_VAD,
      RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_MPRV, KC_VOLD, KC_VOLU, KC_MNXT,
      KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO),

  [_SYMBOLS] = LAYOUT_ortho_4x12(\
      KC_TILD, KC_AT, KC_LCBR, KC_RCBR, KC_PERC,    KC_NO, KC_NO,     KC_COMM, KC_CIRC, KC_AMPR, KC_DLR, KC_DOT,
      KC_EQL, KC_HASH, KC_LPRN, KC_RPRN, KC_PLUS,   KC_NO, KC_NO,     KC_DQUO, KC_SLSH, KC_LT, KC_GT, KC_QUOT,
      KC_GRV, KC_BSLS, KC_LBRC, KC_RBRC, KC_PIPE,   KC_NO, KC_NO,     KC_NO, OS_RSFT, OS_RCTL, OS_LALT, OS_RGUI,
      KC_NO, KC_NO, KC_NO, MO(_MEDIA), KC_SPC,         KC_NO, KC_NO,     KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO
      ),

  [_NUMBERS] = LAYOUT_ortho_4x12(\
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,     KC_NO, KC_NO,     KC_ASTR, KC_7, KC_8, KC_9, KC_SLSH,
      OS_LGUI, OS_LALT, OS_LCTL, KC_TRNS, KC_NO,   KC_NO, KC_NO,     KC_PLUS, KC_4, KC_5, KC_6, KC_EQL,
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,   KC_NO, KC_NO,       KC_MINS, KC_1, KC_2, KC_3, KC_DOT,
      KC_NO, KC_NO, KC_NO, OS_LSFT, KC_SPC,  KC_NO, KC_NO,     KC_0, KC_COMM, KC_NO, KC_NO, KC_NO),


  [_STE_SYM] = LAYOUT_ortho_4x12(\
      KC_NO, KC_EXLM, KC_AT, KC_LCBR, KC_RCBR, KC_PERC,   KC_QUES, KC_CIRC, KC_AMPR, KC_ASTR, KC_QUOT, KC_NO,
      KC_NO, KC_SCLN, KC_COLN, KC_LPRN, KC_RPRN, KC_MINS, KC_PLUS, KC_LT, KC_GT, KC_UNDS, KC_DQUO, KC_ESC,
      KC_TRNS, KC_GRV, KC_BSLS, KC_LBRC, KC_RBRC, KC_EQL,   KC_PIPE, KC_TILD, KC_COMM, KC_DOT, KC_SLSH, KC_TAB,
      KC_NO, KC_NO, KC_NO, KC_HASH, KC_DLR, KC_SPC, KC_BSPC, KC_ENT, KC_DEL, KC_NO, KC_NO, KC_NO
      ),

  [_STE_NAV] = LAYOUT_ortho_4x12(\
      KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
      KC_TRNS, KC_NO, KC_NO, SW_WIN, SW_TAB, KC_NO, KC_NO, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_CAPS,
      KC_NO,  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_HOME, RSFT_PGDN, RCTL_PGUP, LALT_END, RGUI_INS,
      KC_NO, KC_NO, KC_NO, KC_TAB, KC_ESC, KC_SPC, KC_BSPC, KC_ENT, KC_DEL, KC_NO, KC_NO, KC_NO
      ),


};


// Runs just one time when the keyboard initializes.
void matrix_init_user(void) {
  // ...
  steno_set_mode(STENO_MODE_GEMINI);
};


